local lookup = require "main.lookup"

local function modify_speed_of_things(things, delta)
	for _,id in pairs(things) do
		-- the url must reference the script instance where
		-- the property was defined
		print(id)
		local url = msg.url(nil, id, "script")

		local dir = math.random(1, 4)
		local change = math.random(30, 200)

		print("moving")
		print(dir, change)

	end
end

local function random_position()
	return vmath.vector3(math.random(1, sys.get_config("display.width")),  math.random(1, sys.get_config("display.height")), 0)
end

function init(self)
	self.things = {}
	math.randomseed(os.time())
	for i=1,10 do
		print("creating some things")
		local name = "Foo" .. i
		local key = hash(name)
		lookup.add(key, name)
		local id = factory.create("#agent_factory", random_position(), nil, {
			move_to = random_position(),
			move_speed = math.random(100, 300),
			key = key,
			-- color = vmath.vector4(math.random(1, 100) / 100, math.random(1, 100) / 100, math.random(1, 100) / 100, 1),
			-- rotation = vmath.quat_rotation_z(math.random(1, 360) * 180 / math.pi),
			url = msg.url() })
			table.insert(self.things, id)
		end
	end

	function on_message(self, message_id, message, sender)
		print(message_id, sender)
	end