go.property("move_to", vmath.vector3())
go.property("move_speed", 2)
go.property("key", hash(""))
go.property("url", msg.url())
go.property("color", vmath.vector4(1, 1, 1, 1))
go.property("rotation", vmath.quat())

local lookup = require "main.lookup"

local width = tonumber(sys.get_config("display.width"))
local height = tonumber(sys.get_config("display.height"))

function init(self)
    print("My name is " .. lookup.get(self.key))
    print(self.cool and "I'm cool" or "I'm not cool")
    msg.post(self.url, "thing_created")
    self.target = vmath.vector3(math.random(0, width), math.random(0, height), 0)
end

-- manhatten distance
function dist(curr_pos, tgt_pos)
   return math.abs((curr_pos.x - tgt_pos.x) + (curr_pos.y - tgt_pos.y))
end

function update(self, dt)
   local min_dist = self.move_speed / 2
   local speed = vmath.vector3(0, 0, 0)
   local pos = go.get_position()
   local tgt = self.target
   local dist = dist(pos, tgt)
   local dy = pos.y - tgt.y
   local dx = pos.x - tgt.x
   if dx == 0 then
      speed.x = 0
   elseif dx < 0 then
      speed.x = math.min(-dx, self.move_speed)
   else
      speed.x = -math.min(dx, self.move_speed)
   end

   if dy == 0 then
      speed.y = 0
   elseif dy < 0 then
      speed.y = math.min(-dy, self.move_speed)
   else
      speed.y = -math.min(dy, self.move_speed)
   end

   if dist < min_dist then
      self.target = vmath.vector3(math.random(0, width), math.random(0, height), 0)
   end

   -- print(self.move_speed, dist, go.get_position(), self.target)
   go.set_position(pos + speed * dt)
end
